SET NUMERIC_ROUNDABORT OFF
GO
SET XACT_ABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO

--PRE DDL
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO
--DDL
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO
--POST DDL
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO


--PRE DML
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO
--DML
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO
--POST DML
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO


--PRE ROUTINE
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO
--ROUTINE
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO
--POST ROUTINE
BEGIN TRANSACTION Data_Type_Definition
	SET DEADLOCK_PRIORITY HIGH
COMMIT TRANSACTION Data_Type_Definition
GO